#!/bin/bash
# Automate Kopi Upgrade by NodesVault

if command -v jq &> /dev/null; then
    echo "jq installed"
else
    echo "Installing jq..."
    apt update && apt install jq -y
fi
wget -O kopid https://github.com/kopi-money/kopi/releases/download/v11/kopid-v11-linux-amd64 && chmod +x kopid
rpc_port=$(grep -m 1 -oP '^laddr = "\K[^"]+' "$HOME/.kopid/config/config.toml" | cut -d ':' -f 3)
kopiloc=$(which kopid)
while :
do
  cheight=$(curl -s localhost:$rpc_port/status | jq -r .result.sync_info.latest_block_height)
  [ $cheight -ge 3943500 ] && mv kopid $kopiloc && systemctl restart kopid && break
  echo Block left: $((3943500 - cheight))
  sleep 15
done
